// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package resume_schema

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "reflect"

type Job struct {
	// The company offering the role, e.g. 'Microsoft'.
	Company *string `json:"company,omitempty" yaml:"company,omitempty" mapstructure:"company,omitempty"`

	// The date the job was posted in ISO8601 format.
	Date *Iso8601 `json:"date,omitempty" yaml:"date,omitempty" mapstructure:"date,omitempty"`

	// A short description about the job.
	Description *string `json:"description,omitempty" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// The experience level required for the job, e.g. 'Senior', 'Junior',
	// 'Mid-level'.
	Experience *ExperienceLevel `json:"experience,omitempty" yaml:"experience,omitempty" mapstructure:"experience,omitempty"`

	// A list of keywords pertaining to the listing; sourced from the qualifications
	// (required and optional), job description, and responsibilities.
	Keywords Keywords `json:"keywords,omitempty" yaml:"keywords,omitempty" mapstructure:"keywords,omitempty"`

	// Where the job is located. For fully remote jobs, simply fill in the country
	// code of the position and leave the other fields as `null`.
	Location *Location `json:"location,omitempty" yaml:"location,omitempty" mapstructure:"location,omitempty"`

	// Meta corresponds to the JSON schema field "meta".
	Meta Meta `json:"meta" yaml:"meta" mapstructure:"meta"`

	// A list of the qualifications that are optional for this position.
	OptionalQualifications []string `json:"optionalQualifications,omitempty" yaml:"optionalQualifications,omitempty" mapstructure:"optionalQualifications,omitempty"`

	// A list of the qualifications that are required for this position.
	Qualifications []string `json:"qualifications,omitempty" yaml:"qualifications,omitempty" mapstructure:"qualifications,omitempty"`

	// The level of remote work available, where 'Full' is fully online and 'None' is
	// strictly in-person.
	Remote *JobRemote `json:"remote,omitempty" yaml:"remote,omitempty" mapstructure:"remote,omitempty"`

	// What the job entails.
	Responsibilities []string `json:"responsibilities,omitempty" yaml:"responsibilities,omitempty" mapstructure:"responsibilities,omitempty"`

	// The expected salary or range of salaries plus the base time unit, e.g.
	// $100,000/yearly, $5,000 - $6,000/monthly, $25/hourly.
	Salary *string `json:"salary,omitempty" yaml:"salary,omitempty" mapstructure:"salary,omitempty"`

	// A list of the skills utilized while doing work for the job.
	Skills []JobSkillsElem `json:"skills,omitempty" yaml:"skills,omitempty" mapstructure:"skills,omitempty"`

	// The name of the job, e.g. 'Web Developer'.
	Title *string `json:"title,omitempty" yaml:"title,omitempty" mapstructure:"title,omitempty"`

	// The type of job this is, e.g. Full-time, part-time, contract, etc.
	Type *JobType `json:"type,omitempty" yaml:"type,omitempty" mapstructure:"type,omitempty"`
}

type JobRemote string

const JobRemoteFull JobRemote = "Full"
const JobRemoteHybrid JobRemote = "Hybrid"
const JobRemoteNone JobRemote = "None"

var enumValues_JobRemote = []interface{}{
	"Full",
	"Hybrid",
	"None",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *JobRemote) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_JobRemote {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_JobRemote, v)
	}
	*j = JobRemote(v)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *JobRemote) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_JobRemote {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_JobRemote, v)
	}
	*j = JobRemote(v)
	return nil
}

type JobSkillsElem struct {
	// A list of keywords pertaining to this specific skill.
	Keywords Keywords `json:"keywords,omitempty" yaml:"keywords,omitempty" mapstructure:"keywords,omitempty"`

	// The mastery level of the skill.
	Level *MasteryLevel `json:"level,omitempty" yaml:"level,omitempty" mapstructure:"level,omitempty"`

	// The name of the skill, e.g. 'Web Development'.
	Name *string `json:"name,omitempty" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Job) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["meta"]; raw != nil && !ok {
		return fmt.Errorf("field meta in Job: required")
	}
	type Plain Job
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Job(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Job) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["meta"]; raw != nil && !ok {
		return fmt.Errorf("field meta in Job: required")
	}
	type Plain Job
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = Job(plain)
	return nil
}
