// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package resume_schema

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "reflect"
import "regexp"
import "time"

type ExperienceLevel string

const ExperienceLevelDirector ExperienceLevel = "Director"
const ExperienceLevelEntryLevel ExperienceLevel = "Entry-level"
const ExperienceLevelExecutive ExperienceLevel = "Executive"
const ExperienceLevelInternship ExperienceLevel = "Internship"
const ExperienceLevelJunior ExperienceLevel = "Junior"
const ExperienceLevelLead ExperienceLevel = "Lead"
const ExperienceLevelMidLevel ExperienceLevel = "Mid-level"
const ExperienceLevelSenior ExperienceLevel = "Senior"

var enumValues_ExperienceLevel = []interface{}{
	"Internship",
	"Entry-level",
	"Junior",
	"Mid-level",
	"Senior",
	"Lead",
	"Director",
	"Executive",
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *ExperienceLevel) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ExperienceLevel {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ExperienceLevel, v)
	}
	*j = ExperienceLevel(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExperienceLevel) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ExperienceLevel {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ExperienceLevel, v)
	}
	*j = ExperienceLevel(v)
	return nil
}

// Similar to the standard date type, but each section after the year is optional.
// e.g. 2014-06-29 or 2023-04. The value can also be an empty string for ongoing
// dates.
type Iso8601 string

// UnmarshalJSON implements json.Unmarshaler.
func (j *Iso8601) UnmarshalJSON(value []byte) error {
	type Plain Iso8601
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^([1-2][0-9]{3}-[0-1][0-9]-[0-3][0-9]|[1-2][0-9]{3}-[0-1][0-9]|[1-2][0-9]{3}|)$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^([1-2][0-9]{3}-[0-1][0-9]-[0-3][0-9]|[1-2][0-9]{3}-[0-1][0-9]|[1-2][0-9]{3}|)$`)
	}
	*j = Iso8601(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Iso8601) UnmarshalYAML(value *yaml.Node) error {
	type Plain Iso8601
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^([1-2][0-9]{3}-[0-1][0-9]-[0-3][0-9]|[1-2][0-9]{3}-[0-1][0-9]|[1-2][0-9]{3}|)$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^([1-2][0-9]{3}-[0-1][0-9]-[0-3][0-9]|[1-2][0-9]{3}-[0-1][0-9]|[1-2][0-9]{3}|)$`)
	}
	*j = Iso8601(plain)
	return nil
}

type JobType string

const JobTypeContract JobType = "Contract"
const JobTypeFullTime JobType = "Full-Time"
const JobTypeOnDemand JobType = "On-Demand"
const JobTypePartTime JobType = "Part-Time"
const JobTypeSeasonal JobType = "Seasonal"
const JobTypeUnspecified JobType = "Unspecified"

var enumValues_JobType = []interface{}{
	"Part-Time",
	"Full-Time",
	"Seasonal",
	"On-Demand",
	"Contract",
	"Unspecified",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *JobType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_JobType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_JobType, v)
	}
	*j = JobType(v)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *JobType) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_JobType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_JobType, v)
	}
	*j = JobType(v)
	return nil
}

// A list of keywords that are related to the parent object. Due to the nature of
// being keywords, the items within may have aliases attached. However, each item
// should appear ONCE and matched on using a separate dictionary to keep this array
// as slim as possible.
type Keywords []string

// A location in the world. Can be a full address, a partial address, or simply a
// listing of the country and region.
type Location struct {
	// The street name and number components of the location.
	Address *string `json:"address,omitempty" yaml:"address,omitempty" mapstructure:"address,omitempty"`

	// City corresponds to the JSON schema field "city".
	City *string `json:"city,omitempty" yaml:"city,omitempty" mapstructure:"city,omitempty"`

	// Country code as per ISO-3166-1 ALPHA-2, e.g. US, AU, IN.
	CountryCode *string `json:"countryCode,omitempty" yaml:"countryCode,omitempty" mapstructure:"countryCode,omitempty"`

	// Also known as a zip code for US addresses.
	PostalCode *string `json:"postalCode,omitempty" yaml:"postalCode,omitempty" mapstructure:"postalCode,omitempty"`

	// Can be a state, province, prefecture, oblast, etc.
	Region *string `json:"region,omitempty" yaml:"region,omitempty" mapstructure:"region,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Location) UnmarshalJSON(value []byte) error {
	type Plain Location
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.CountryCode != nil {
		if matched, _ := regexp.MatchString(`[A-Z]{2}`, string(*plain.CountryCode)); !matched {
			return fmt.Errorf("field %s pattern match: must match %s", "CountryCode", `[A-Z]{2}`)
		}
	}
	*j = Location(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Location) UnmarshalYAML(value *yaml.Node) error {
	type Plain Location
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if plain.CountryCode != nil {
		if matched, _ := regexp.MatchString(`[A-Z]{2}`, string(*plain.CountryCode)); !matched {
			return fmt.Errorf("field %s pattern match: must match %s", "CountryCode", `[A-Z]{2}`)
		}
	}
	*j = Location(plain)
	return nil
}

type MasteryLevel string

const MasteryLevelAdvanced MasteryLevel = "Advanced"
const MasteryLevelExpert MasteryLevel = "Expert"
const MasteryLevelIntermediate MasteryLevel = "Intermediate"
const MasteryLevelMaster MasteryLevel = "Master"
const MasteryLevelNovice MasteryLevel = "Novice"

var enumValues_MasteryLevel = []interface{}{
	"Novice",
	"Intermediate",
	"Advanced",
	"Expert",
	"Master",
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *MasteryLevel) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MasteryLevel {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MasteryLevel, v)
	}
	*j = MasteryLevel(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MasteryLevel) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MasteryLevel {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MasteryLevel, v)
	}
	*j = MasteryLevel(v)
	return nil
}

// The schema version and any other tooling configuration lives here.
type Meta struct {
	// URL (as per RFC 3986) to latest version of this document.
	Canonical *string `json:"canonical,omitempty" yaml:"canonical,omitempty" mapstructure:"canonical,omitempty"`

	// Using ISO 8601 with 'YYYY-MM-DDThh:mm:ss'.
	LastModified *time.Time `json:"lastModified,omitempty" yaml:"lastModified,omitempty" mapstructure:"lastModified,omitempty"`

	// A version field which follows semver - e.g. `1.0.0`. Regexp is per the
	// recommendation of semver.org
	Version string `json:"version" yaml:"version" mapstructure:"version"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Meta) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in Meta: required")
	}
	type Plain Meta
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$`, string(plain.Version)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Version", `^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$`)
	}
	*j = Meta(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Meta) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in Meta: required")
	}
	type Plain Meta
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$`, string(plain.Version)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Version", `^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$`)
	}
	*j = Meta(plain)
	return nil
}

type TypesJson map[string]interface{}
