// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package go_resume_schema

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "reflect"

type Resume struct {
	// A list of awards and distinctions received, sorted chronologically from latest
	// to earliest.
	Awards []ResumeAwardsElem `json:"awards,omitempty,omitzero" yaml:"awards,omitempty" mapstructure:"awards,omitempty"`

	// Basics corresponds to the JSON schema field "basics".
	Basics *ResumeBasics `json:"basics,omitempty,omitzero" yaml:"basics,omitempty" mapstructure:"basics,omitempty"`

	// A list of certificates awarded, sorted chronologically from latest to earliest.
	Certificates []ResumeCertificatesElem `json:"certificates,omitempty,omitzero" yaml:"certificates,omitempty" mapstructure:"certificates,omitempty"`

	// A list of past and present institutions attended, sorted chronologically from
	// latest to earliest.
	Education []ResumeEducationElem `json:"education,omitempty,omitzero" yaml:"education,omitempty" mapstructure:"education,omitempty"`

	// A list of personal interests that lie outside one's professional work (i.e.
	// hobbies).
	Interests []ResumeInterestsElem `json:"interests,omitempty,omitzero" yaml:"interests,omitempty" mapstructure:"interests,omitempty"`

	// A list of languages spoken and/or written.
	Languages []ResumeLanguagesElem `json:"languages,omitempty,omitzero" yaml:"languages,omitempty" mapstructure:"languages,omitempty"`

	// Meta corresponds to the JSON schema field "meta".
	Meta Meta `json:"meta" yaml:"meta" mapstructure:"meta"`

	// A list of past and present professional or personal projects done, sorted
	// chronologically from latest to earliest.
	Projects []ResumeProjectsElem `json:"projects,omitempty,omitzero" yaml:"projects,omitempty" mapstructure:"projects,omitempty"`

	// A list of past and present publications made, sorted chronologically from
	// latest to earliest.
	Publications []ResumePublicationsElem `json:"publications,omitempty,omitzero" yaml:"publications,omitempty" mapstructure:"publications,omitempty"`

	// A list of references/letters of recommendation received.
	References []ResumeReferencesElem `json:"references,omitempty,omitzero" yaml:"references,omitempty" mapstructure:"references,omitempty"`

	// A list of professional skills, including their mastery level.
	Skills []ResumeSkillsElem `json:"skills,omitempty,omitzero" yaml:"skills,omitempty" mapstructure:"skills,omitempty"`

	// A list of past and present volunteer work done, sorted chronologically from
	// latest to earliest.
	Volunteer []ResumeVolunteerElem `json:"volunteer,omitempty,omitzero" yaml:"volunteer,omitempty" mapstructure:"volunteer,omitempty"`

	// A list of past and present professional work done, sorted chronologically from
	// latest to earliest.
	Work []ResumeWorkElem `json:"work,omitempty,omitzero" yaml:"work,omitempty" mapstructure:"work,omitempty"`
}

type ResumeAwardsElem struct {
	// The organization or entity that conferred the award, e.g. 'Time Magazine'.
	Awarder *string `json:"awarder,omitempty,omitzero" yaml:"awarder,omitempty" mapstructure:"awarder,omitempty"`

	// Date corresponds to the JSON schema field "date".
	Date *Iso8601 `json:"date,omitempty,omitzero" yaml:"date,omitempty" mapstructure:"date,omitempty"`

	// A list of keywords pertaining to this award.
	Keywords Keywords `json:"keywords,omitempty,omitzero" yaml:"keywords,omitempty" mapstructure:"keywords,omitempty"`

	// A short 1-2 sentence description of the award, e.g. 'Received for my work with
	// Quantum Physics'.
	Summary *string `json:"summary,omitempty,omitzero" yaml:"summary,omitempty" mapstructure:"summary,omitempty"`

	// The title of the award, e.g. 'Nobel Peace Prize'.
	Title *string `json:"title,omitempty,omitzero" yaml:"title,omitempty" mapstructure:"title,omitempty"`
}

type ResumeBasics struct {
	// The subject's email address, e.g. 'thomas@gmail.com'.
	Email *string `json:"email,omitempty,omitzero" yaml:"email,omitempty" mapstructure:"email,omitempty"`

	// URL (as per RFC 3986) to an image in JPEG or PNG format.
	Image *string `json:"image,omitempty,omitzero" yaml:"image,omitempty" mapstructure:"image,omitempty"`

	// The subject's professional title, e.g. Web Developer.
	Label *string `json:"label,omitempty,omitzero" yaml:"label,omitempty" mapstructure:"label,omitempty"`

	// A list of web links relevant to the subject, e.g. personal website, social
	// media, portfolios, etc.
	Links []ResumeBasicsLinksElem `json:"links,omitempty,omitzero" yaml:"links,omitempty" mapstructure:"links,omitempty"`

	// Where the subject is from. Can be a general region or their exact home address.
	Location *Location `json:"location,omitempty,omitzero" yaml:"location,omitempty" mapstructure:"location,omitempty"`

	// The name of the resume's subject.
	Name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// The contact phone number of the subject. Phone numbers are stored as strings so
	// use any format preferred, e.g.'712-117-2923'.
	Phone *string `json:"phone,omitempty,omitzero" yaml:"phone,omitempty" mapstructure:"phone,omitempty"`

	// A short 2-3 sentence biography about the subject.
	Summary *string `json:"summary,omitempty,omitzero" yaml:"summary,omitempty" mapstructure:"summary,omitempty"`
}

type ResumeBasicsLinksElem struct {
	// The label for the hyperlink, e.g. '@johndoe'.
	Label *string `json:"label,omitempty,omitzero" yaml:"label,omitempty" mapstructure:"label,omitempty"`

	// e.g. https://github.com/johndoe
	Url *string `json:"url,omitempty,omitzero" yaml:"url,omitempty" mapstructure:"url,omitempty"`
}

type ResumeCertificatesElem struct {
	// The date the certificate was issued.
	Date *Iso8601 `json:"date,omitempty,omitzero" yaml:"date,omitempty" mapstructure:"date,omitempty"`

	// The ID number of the certificate for verification purposes, if applicable.
	Id *string `json:"id,omitempty,omitzero" yaml:"id,omitempty" mapstructure:"id,omitempty"`

	// The organization or entity that awarded the certificate, e.g. 'CNCF'.
	Issuer *string `json:"issuer,omitempty,omitzero" yaml:"issuer,omitempty" mapstructure:"issuer,omitempty"`

	// A list of keywords pertaining to this certificate.
	Keywords Keywords `json:"keywords,omitempty,omitzero" yaml:"keywords,omitempty" mapstructure:"keywords,omitempty"`

	// The title of the certificate, e.g. 'Certified Kubernetes Administrator'.
	Name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// The relevant URL of the awarding organization's homepage, e.g.
	// 'http://example.com'.
	Url *string `json:"url,omitempty,omitzero" yaml:"url,omitempty" mapstructure:"url,omitempty"`
}

type ResumeEducationElem struct {
	// The broad area of study, e.g. 'Engineering', 'Humanities'.
	Area *string `json:"area,omitempty,omitzero" yaml:"area,omitempty" mapstructure:"area,omitempty"`

	// Awards or honors earned for this program, e.g. 'Dean's List', 'Graduated with
	// Honors'.
	Awards []string `json:"awards,omitempty,omitzero" yaml:"awards,omitempty" mapstructure:"awards,omitempty"`

	// A list of relevant courses/subjects.
	Courses []string `json:"courses,omitempty,omitzero" yaml:"courses,omitempty" mapstructure:"courses,omitempty"`

	// The date on which the education at this institution was stopped. If current and
	// ongoing, specify a blank string as the value for this key.
	EndDate *Iso8601 `json:"endDate,omitempty,omitzero" yaml:"endDate,omitempty" mapstructure:"endDate,omitempty"`

	// A list of relevant extracurricular activities participated in while a student
	// at the institution, e.g. 'Bird Watching Club', 'Association of Computing
	// Machinery'.
	Extracurriculars []string `json:"extracurriculars,omitempty,omitzero" yaml:"extracurriculars,omitempty" mapstructure:"extracurriculars,omitempty"`

	// The cumulative grade point average (GPA), e.g. '3.67/4.0'.
	Gpa *string `json:"gpa,omitempty,omitzero" yaml:"gpa,omitempty" mapstructure:"gpa,omitempty"`

	// A list of honor societies inducted into during the completion of education at
	// this institution.
	HonorSocieties []ResumeEducationElemHonorSocietiesElem `json:"honorSocieties,omitempty,omitzero" yaml:"honorSocieties,omitempty" mapstructure:"honorSocieties,omitempty"`

	// The name of the institution being attended, e.g. 'Massachusetts Institute of
	// Technology'.
	Institution *string `json:"institution,omitempty,omitzero" yaml:"institution,omitempty" mapstructure:"institution,omitempty"`

	// A list of keywords pertaining to this education.
	Keywords Keywords `json:"keywords,omitempty,omitzero" yaml:"keywords,omitempty" mapstructure:"keywords,omitempty"`

	// The location of the institution, e.g. 'Boston, MA'.
	Location *string `json:"location,omitempty,omitzero" yaml:"location,omitempty" mapstructure:"location,omitempty"`

	// Optional free-text notes, e.g. 'part-time study', 'transfer credits'.
	Notes *string `json:"notes,omitempty,omitzero" yaml:"notes,omitempty" mapstructure:"notes,omitempty"`

	// One or more programs/majors pursued at this institution. Each item includes a
	// degree designation and a name.
	Programs []ResumeEducationElemProgramsElem `json:"programs,omitempty,omitzero" yaml:"programs,omitempty" mapstructure:"programs,omitempty"`

	// The date on which the education at this institution was started.
	StartDate *Iso8601 `json:"startDate,omitempty,omitzero" yaml:"startDate,omitempty" mapstructure:"startDate,omitempty"`

	// A specific college/school/department within the institution, e.g. 'College of
	// Arts and Humanities'.
	SubInstitution *string `json:"subInstitution,omitempty,omitzero" yaml:"subInstitution,omitempty" mapstructure:"subInstitution,omitempty"`

	// The relevant URL of the sub-institution's homepage, if different, e.g.
	// 'https://example.com.edu/arts-humanities'.
	SubInstitutionUrl *string `json:"subInstitutionUrl,omitempty,omitzero" yaml:"subInstitutionUrl,omitempty" mapstructure:"subInstitutionUrl,omitempty"`

	// The relevant URL of the institution's homepage, e.g. 'http://example.com.edu'.
	Url *string `json:"url,omitempty,omitzero" yaml:"url,omitempty" mapstructure:"url,omitempty"`
}

type ResumeEducationElemHonorSocietiesElem struct {
	// The specific chapter of the honor society, if applicable, e.g. 'Omega'.
	Chapter *string `json:"chapter,omitempty,omitzero" yaml:"chapter,omitempty" mapstructure:"chapter,omitempty"`

	// The date of induction into the honor society.
	InductionDate *Iso8601 `json:"inductionDate,omitempty,omitzero" yaml:"inductionDate,omitempty" mapstructure:"inductionDate,omitempty"`

	// The relevant membership ID, if applicable.
	MemberId *string `json:"memberId,omitempty,omitzero" yaml:"memberId,omitempty" mapstructure:"memberId,omitempty"`

	// The name of the honor society, e.g. 'Phi Beta Kappa'.
	Name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}

type ResumeEducationElemProgramsElem struct {
	// Concentration or track within the major/minor, if applicable, e.g., 'Artificial
	// Intelligence'.
	Concentration *string `json:"concentration,omitempty,omitzero" yaml:"concentration,omitempty" mapstructure:"concentration,omitempty"`

	// The degree designation or abbreviation of it, e.g. 'Bachelor of Science/B.S.',
	// 'Master of Arts/M.A.', 'Associate of Applied Science/A.A.S'.
	Designation *string `json:"designation,omitempty,omitzero" yaml:"designation,omitempty" mapstructure:"designation,omitempty"`

	// The cumulative grade point average (GPA) for this program, e.g. '3.67/4.0'.
	Gpa *string `json:"gpa,omitempty,omitzero" yaml:"gpa,omitempty" mapstructure:"gpa,omitempty"`

	// Honors or distinctions associated with this program, e.g., 'Summa Cum Laude'.
	Honors *string `json:"honors,omitempty,omitzero" yaml:"honors,omitempty" mapstructure:"honors,omitempty"`

	// Indicates if this program is a minor rather than a major.
	Minor *bool `json:"minor,omitempty,omitzero" yaml:"minor,omitempty" mapstructure:"minor,omitempty"`

	// Specific major/minor name, e.g. 'Computer Science', 'Economics'.
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// The broad education type for this program.
	Type ResumeEducationElemProgramsElemType `json:"type" yaml:"type" mapstructure:"type"`
}

type ResumeEducationElemProgramsElemType string

const ResumeEducationElemProgramsElemTypeCertificate ResumeEducationElemProgramsElemType = "Certificate"
const ResumeEducationElemProgramsElemTypeDegree ResumeEducationElemProgramsElemType = "Degree"
const ResumeEducationElemProgramsElemTypeDiploma ResumeEducationElemProgramsElemType = "Diploma"
const ResumeEducationElemProgramsElemTypeNonDegree ResumeEducationElemProgramsElemType = "Non-Degree"
const ResumeEducationElemProgramsElemTypeOther ResumeEducationElemProgramsElemType = "Other"
const ResumeEducationElemProgramsElemTypeProfessional ResumeEducationElemProgramsElemType = "Professional"

var enumValues_ResumeEducationElemProgramsElemType = []interface{}{
	"Degree",
	"Certificate",
	"Diploma",
	"Non-Degree",
	"Professional",
	"Other",
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *ResumeEducationElemProgramsElemType) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ResumeEducationElemProgramsElemType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ResumeEducationElemProgramsElemType, v)
	}
	*j = ResumeEducationElemProgramsElemType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ResumeEducationElemProgramsElemType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ResumeEducationElemProgramsElemType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ResumeEducationElemProgramsElemType, v)
	}
	*j = ResumeEducationElemProgramsElemType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ResumeEducationElemProgramsElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in ResumeEducationElemProgramsElem: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in ResumeEducationElemProgramsElem: required")
	}
	type Plain ResumeEducationElemProgramsElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ResumeEducationElemProgramsElem(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *ResumeEducationElemProgramsElem) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in ResumeEducationElemProgramsElem: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in ResumeEducationElemProgramsElem: required")
	}
	type Plain ResumeEducationElemProgramsElem
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = ResumeEducationElemProgramsElem(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *ResumeEducationElem) UnmarshalYAML(value *yaml.Node) error {
	type Plain ResumeEducationElem
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if plain.Programs != nil && len(plain.Programs) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "programs", 1)
	}
	*j = ResumeEducationElem(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ResumeEducationElem) UnmarshalJSON(value []byte) error {
	type Plain ResumeEducationElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Programs != nil && len(plain.Programs) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "programs", 1)
	}
	*j = ResumeEducationElem(plain)
	return nil
}

type ResumeInterestsElem struct {
	// A list of keywords pertaining to this interest.
	Keywords Keywords `json:"keywords,omitempty,omitzero" yaml:"keywords,omitempty" mapstructure:"keywords,omitempty"`

	// The name of the interest, e.g. 'Philosophy'.
	Name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}

type ResumeLanguagesElem struct {
	// The proficiency in utilizing this language according to the CEFR.
	Fluency *ResumeLanguagesElemFluency `json:"fluency,omitempty,omitzero" yaml:"fluency,omitempty" mapstructure:"fluency,omitempty"`

	// e.g. English, Spanish
	Language *string `json:"language,omitempty,omitzero" yaml:"language,omitempty" mapstructure:"language,omitempty"`
}

type ResumeLanguagesElemFluency string

const ResumeLanguagesElemFluencyAdvanced ResumeLanguagesElemFluency = "Advanced"
const ResumeLanguagesElemFluencyBeginner ResumeLanguagesElemFluency = "Beginner"
const ResumeLanguagesElemFluencyIntermediate ResumeLanguagesElemFluency = "Intermediate"
const ResumeLanguagesElemFluencyNative ResumeLanguagesElemFluency = "Native"
const ResumeLanguagesElemFluencyProficient ResumeLanguagesElemFluency = "Proficient"

var enumValues_ResumeLanguagesElemFluency = []interface{}{
	"Beginner",
	"Intermediate",
	"Advanced",
	"Proficient",
	"Native",
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *ResumeLanguagesElemFluency) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ResumeLanguagesElemFluency {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ResumeLanguagesElemFluency, v)
	}
	*j = ResumeLanguagesElemFluency(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ResumeLanguagesElemFluency) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ResumeLanguagesElemFluency {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ResumeLanguagesElemFluency, v)
	}
	*j = ResumeLanguagesElemFluency(v)
	return nil
}

type ResumeProjectsElem struct {
	// A short summary of project in 1-3 sentences. e.g. 'Collated works of 2017'.
	Description *string `json:"description,omitempty,omitzero" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// The date on which work on this project was stopped. If current and ongoing,
	// specify a blank string as the value for this key.
	EndDate *Iso8601 `json:"endDate,omitempty,omitzero" yaml:"endDate,omitempty" mapstructure:"endDate,omitempty"`

	// The relevant company/entity affiliations, if any, e.g. 'greenpeace',
	// 'corporationXYZ'.
	Entity *string `json:"entity,omitempty,omitzero" yaml:"entity,omitempty" mapstructure:"entity,omitempty"`

	// A list of the key highlights of the project. For best results, use the XYZ
	// formula with quantifiable attributes.
	Highlights []string `json:"highlights,omitempty,omitzero" yaml:"highlights,omitempty" mapstructure:"highlights,omitempty"`

	// A list of keywords pertaining to this project.
	Keywords Keywords `json:"keywords,omitempty,omitzero" yaml:"keywords,omitempty" mapstructure:"keywords,omitempty"`

	// The name of the project, e.g. 'The World Wide Web'.
	Name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// A list of the roles taken on during the development of the project.
	Roles []string `json:"roles,omitempty,omitzero" yaml:"roles,omitempty" mapstructure:"roles,omitempty"`

	// The date on which work on this project was started.
	StartDate *Iso8601 `json:"startDate,omitempty,omitzero" yaml:"startDate,omitempty" mapstructure:"startDate,omitempty"`

	//  e.g. 'volunteering', 'presentation', 'talk', 'application', 'conference'
	Type *string `json:"type,omitempty,omitzero" yaml:"type,omitempty" mapstructure:"type,omitempty"`

	// e.g. http://www.computer.org/csdl/mags/co/1996/10/rx069-abs.html
	Url *string `json:"url,omitempty,omitzero" yaml:"url,omitempty" mapstructure:"url,omitempty"`
}

type ResumePublicationsElem struct {
	// A list of keywords pertaining to this publication.
	Keywords Keywords `json:"keywords,omitempty,omitzero" yaml:"keywords,omitempty" mapstructure:"keywords,omitempty"`

	// The name of the publication, e.g. 'The World Wide Web'.
	Name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// The name of the organization or entity that published the publication, e.g.
	// 'IEEE, Computer Magazine'.
	Publisher *string `json:"publisher,omitempty,omitzero" yaml:"publisher,omitempty" mapstructure:"publisher,omitempty"`

	// The date of the publication.
	ReleaseDate *Iso8601 `json:"releaseDate,omitempty,omitzero" yaml:"releaseDate,omitempty" mapstructure:"releaseDate,omitempty"`

	// A short summary of publication, e.g. 'Discussion of the World Wide Web, HTTP,
	// HTML'.
	Summary *string `json:"summary,omitempty,omitzero" yaml:"summary,omitempty" mapstructure:"summary,omitempty"`

	// e.g. http://www.computer.org.example.com/csdl/mags/co/1996/10/rx069-abs.html
	Url *string `json:"url,omitempty,omitzero" yaml:"url,omitempty" mapstructure:"url,omitempty"`
}

type ResumeReferencesElem struct {
	// The person who wrote the reference, e.g. 'Timothy Cook'.
	Name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// e.g. Joe blogs was a great employee, who turned up to work at least once a
	// week. He exceeded my expectations when it came to doing nothing.
	Reference *string `json:"reference,omitempty,omitzero" yaml:"reference,omitempty" mapstructure:"reference,omitempty"`
}

type ResumeSkillsElem struct {
	// A list of keywords pertaining to this skill.
	Keywords Keywords `json:"keywords,omitempty,omitzero" yaml:"keywords,omitempty" mapstructure:"keywords,omitempty"`

	// The experience level of the skill, e.g. 'Novice', 'Intermediate', 'Advanced',
	// etc.
	Level *MasteryLevel `json:"level,omitempty,omitzero" yaml:"level,omitempty" mapstructure:"level,omitempty"`

	// The name of the skill, e.g. 'Web Development'.
	Name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}

type ResumeVolunteerElem struct {
	// The date on which this volunteer position was stopped. If current and ongoing,
	// specify a blank string as the value for this key.
	EndDate *Iso8601 `json:"endDate,omitempty,omitzero" yaml:"endDate,omitempty" mapstructure:"endDate,omitempty"`

	// A list of the key highlights of the volunteer role. For best results, use the
	// XYZ formula with quantifiable attributes.
	Highlights []string `json:"highlights,omitempty,omitzero" yaml:"highlights,omitempty" mapstructure:"highlights,omitempty"`

	// A list of keywords pertaining to this volunteer position.
	Keywords Keywords `json:"keywords,omitempty,omitzero" yaml:"keywords,omitempty" mapstructure:"keywords,omitempty"`

	// The name of the volunteer organization, e.g. 'American Red Cross'.
	Organization *string `json:"organization,omitempty,omitzero" yaml:"organization,omitempty" mapstructure:"organization,omitempty"`

	// The title of the volunteer role, e.g. 'Customer Service Representative'.
	Position *string `json:"position,omitempty,omitzero" yaml:"position,omitempty" mapstructure:"position,omitempty"`

	// The date on which this volunteer position was started.
	StartDate *Iso8601 `json:"startDate,omitempty,omitzero" yaml:"startDate,omitempty" mapstructure:"startDate,omitempty"`

	// An overview of the responsibilities at the volunteer organization. No more than
	// 3-5 sentences.
	Summary *string `json:"summary,omitempty,omitzero" yaml:"summary,omitempty" mapstructure:"summary,omitempty"`

	// The relevant URL of the volunteer organization's homepage, e.g.
	// 'http://redcross.example.com'.
	Url *string `json:"url,omitempty,omitzero" yaml:"url,omitempty" mapstructure:"url,omitempty"`
}

type ResumeWorkElem struct {
	// A short, 1 sentence maximum description of the company, e.g. 'Social Media
	// Company'.
	Description *string `json:"description,omitempty,omitzero" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// The name of the company, e.g. 'Facebook'.
	Employer *string `json:"employer,omitempty,omitzero" yaml:"employer,omitempty" mapstructure:"employer,omitempty"`

	// The date on which this position was stopped. If current and ongoing, specify a
	// blank string as the value for this key.
	EndDate *Iso8601 `json:"endDate,omitempty,omitzero" yaml:"endDate,omitempty" mapstructure:"endDate,omitempty"`

	// A list of the key highlights of the volunteer role. For best results, use the
	// XYZ formula with quantifiable attributes.
	Highlights []string `json:"highlights,omitempty,omitzero" yaml:"highlights,omitempty" mapstructure:"highlights,omitempty"`

	// A list of keywords pertaining to this job position.
	Keywords Keywords `json:"keywords,omitempty,omitzero" yaml:"keywords,omitempty" mapstructure:"keywords,omitempty"`

	// The location the job is/was, e.g. 'Menlo Park, CA'. If the job is/was remote,
	// specify 'Remote'.
	Location *string `json:"location,omitempty,omitzero" yaml:"location,omitempty" mapstructure:"location,omitempty"`

	// The title of the role, e.g. 'Software Engineer'.
	Position *string `json:"position,omitempty,omitzero" yaml:"position,omitempty" mapstructure:"position,omitempty"`

	// The date on which this position was started.
	StartDate *Iso8601 `json:"startDate,omitempty,omitzero" yaml:"startDate,omitempty" mapstructure:"startDate,omitempty"`

	// An overview of the responsibilities at the company. No more than 3-5 sentences.
	Summary *string `json:"summary,omitempty,omitzero" yaml:"summary,omitempty" mapstructure:"summary,omitempty"`

	// The relevant URL of the company's homepage, e.g. 'http://facebook.example.com'.
	Url *string `json:"url,omitempty,omitzero" yaml:"url,omitempty" mapstructure:"url,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Resume) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["meta"]; raw != nil && !ok {
		return fmt.Errorf("field meta in Resume: required")
	}
	type Plain Resume
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Resume(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Resume) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["meta"]; raw != nil && !ok {
		return fmt.Errorf("field meta in Resume: required")
	}
	type Plain Resume
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = Resume(plain)
	return nil
}
